/*
 * TuCSoN coordination infrastructure - Copyright (C) 2001-2002 aliCE team at
 * deis.unibo.it This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of the License,
 * or (at your option) any later version. This library is distributed in the
 * hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See
 * the GNU Lesser General Public License for more details. You should have
 * received a copy of the GNU Lesser General Public License along with this
 * library; if not, write to the Free Software Foundation, Inc., 59 Temple
 * Place, Suite 330, Boston, MA 02111-1307 USA
 */
package alice.tucson.introspection;

import java.io.IOException;
import java.util.List;

import alice.tucson.api.TucsonTupleCentreId;
import alice.tuplecentre.api.Tuple;

/**
 * Defines the basic context for TuCSoN Inspector
 * 
 */
public interface InspectorContext {

    /** waits and processes TuCSoN virtual machine events */
    void acceptVMEvent() throws ClassNotFoundException, IOException;

    /** adds a new listener to the event generated by this context */
    void addInspectorContextListener(InspectorContextListener l);

    /** shutdown inspector */
    void exit() throws IOException;

    /** gets a snapshot of tuple set */
    void getSnapshot(byte snapshotType) throws IOException;

    TucsonTupleCentreId getTid();

    /** when doing trace, asks for a new virtual machine step */
    void nextStep() throws IOException;

    /** Removes a listener to Inspector Events */
    void removeInspectorContextListener(InspectorContextListener l);

    /** resets the tuple centre */
    void reset() throws IOException;

    /** sets the entire content of the event set */
    void setEventSet(List<Tuple> tset) throws IOException;

    /** specifies the protocol used by the inspector */
    void setProtocol(InspectorProtocol p) throws IOException;

    /** sets the entire content of the tuple set */
    void setTupleSet(List<Tuple> tset) throws IOException;

}
